-- BX FOLDER database schema
-- Run this once in Supabase SQL Editor.

create table if not exists public.bx_registrations (
  id bigint generated by default as identity primary key,
  surname text not null check (char_length(surname) between 2 and 60),
  display_name text not null,
  phone text not null unique check (phone ~ '^[0-9]{8,15}$'),
  sex text not null check (sex in ('male', 'female')),
  country text not null check (char_length(country) between 2 and 80),
  consent_vcf boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists bx_registrations_created_at_idx
  on public.bx_registrations (created_at desc);

create or replace function public.bx_enforce_capacity()
returns trigger
language plpgsql
set search_path = public
as $
declare
  current_total bigint;
begin
  perform pg_advisory_xact_lock(50950000);
  select count(*) into current_total from public.bx_registrations;
  if current_total >= 50000 then
    raise exception 'BX_FOLDER_CAPACITY_REACHED';
  end if;
  return new;
end;
$$;

drop trigger if exists bx_capacity_guard on public.bx_registrations;
create trigger bx_capacity_guard
before insert on public.bx_registrations
for each row execute function public.bx_enforce_capacity();

alter table public.bx_registrations enable row level security;
-- No public policies are required: the server uses the service-role key.


alter table public.bx_registrations
  add column if not exists consent_vcf boolean not null default false;
