-- BX FOLDER consolidated schema

create table if not exists public.bx_groups (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 80),
  url text not null unique check (url like 'https://chat.whatsapp.com/%'),
  capacity integer not null default 1024 check (capacity between 1 and 100000),
  assigned_count integer not null default 0 check (assigned_count >= 0),
  enabled boolean not null default true,
  priority integer not null default 100,
  created_at timestamptz not null default now()
);

create table if not exists public.bx_registrations (
  id bigint generated by default as identity primary key,
  surname text not null check (char_length(surname) between 2 and 60),
  display_name text not null,
  phone text not null unique check (phone ~ '^[0-9]{8,15}$'),
  sex text not null check (sex in ('male', 'female')),
  country text not null check (char_length(country) between 2 and 80),
  consent_vcf boolean not null default false,
  group_id bigint references public.bx_groups(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.bx_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.bx_removal_requests (
  id bigint generated by default as identity primary key,
  phone text not null check (phone ~ '^[0-9]{8,15}$'),
  reason text not null default '',
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.bx_rate_limits (
  bucket text not null,
  identity text not null,
  window_start timestamptz not null,
  hits integer not null default 0,
  primary key(bucket, identity, window_start)
);

create index if not exists bx_registrations_created_at_idx on public.bx_registrations(created_at desc);
create index if not exists bx_removal_requests_created_at_idx on public.bx_removal_requests(created_at desc);

alter table public.bx_groups enable row level security;
alter table public.bx_registrations enable row level security;
alter table public.bx_settings enable row level security;
alter table public.bx_removal_requests enable row level security;
alter table public.bx_rate_limits enable row level security;

insert into public.bx_settings(key, value)
values ('maintenance', '{"enabled":false,"message":"BX FOLDER est temporairement en maintenance."}'::jsonb)
on conflict (key) do nothing;

insert into public.bx_groups(name, url, capacity, enabled, priority)
values ('Groupe principal', 'https://chat.whatsapp.com/J2Ewhgf22Jd2RZguLvjTHR', 1024, true, 10)
on conflict (url) do nothing;

create or replace function public.bx_enforce_capacity()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  current_total bigint;
begin
  perform pg_advisory_xact_lock(50950000);
  select count(*) into current_total from public.bx_registrations;
  if current_total >= 50000 then
    raise exception 'BX_FOLDER_CAPACITY_REACHED';
  end if;
  return new;
end;
$$;

drop trigger if exists bx_capacity_guard on public.bx_registrations;
create trigger bx_capacity_guard
before insert on public.bx_registrations
for each row execute function public.bx_enforce_capacity();

create or replace function public.bx_assign_group()
returns table(id bigint, name text, url text, capacity integer, assigned_count integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  chosen public.bx_groups%rowtype;
begin
  select * into chosen
  from public.bx_groups
  where enabled = true and assigned_count < capacity
  order by priority asc, id asc
  for update skip locked
  limit 1;

  if chosen.id is null then return; end if;

  update public.bx_groups
  set assigned_count = bx_groups.assigned_count + 1
  where bx_groups.id = chosen.id
  returning bx_groups.id, bx_groups.name, bx_groups.url, bx_groups.capacity, bx_groups.assigned_count
  into id, name, url, capacity, assigned_count;

  return next;
end;
$$;

create or replace function public.bx_rate_limit_hit(
  p_bucket text, p_identity text, p_window_seconds integer, p_limit integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  w timestamptz;
  n integer;
begin
  w := to_timestamp(floor(extract(epoch from now()) / greatest(1,p_window_seconds)) * greatest(1,p_window_seconds));
  insert into public.bx_rate_limits(bucket, identity, window_start, hits)
  values (p_bucket, p_identity, w, 1)
  on conflict (bucket, identity, window_start)
  do update set hits = bx_rate_limits.hits + 1
  returning hits into n;
  return n <= greatest(1,p_limit);
end;
$$;

create or replace function public.bx_admin_stats()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'total', count(*),
    'male', count(*) filter (where sex = 'male'),
    'female', count(*) filter (where sex = 'female'),
    'today', count(*) filter (where created_at >= date_trunc('day', now())),
    'last7', count(*) filter (where created_at >= now() - interval '7 days'),
    'countries', coalesce((
      select jsonb_agg(jsonb_build_object('country', country, 'count', cnt) order by cnt desc)
      from (
        select country, count(*)::int as cnt
        from public.bx_registrations
        group by country
        order by count(*) desc
        limit 8
      ) c
    ), '[]'::jsonb)
  )
  from public.bx_registrations;
$$;
